project:
  type: website
  output-dir: docs
  render:
    - content/story.md

website:
  title: "Project Draft"
  sidebar:
    search: true
  navbar:
    right:
      - icon: github
        href: https://github.com/Starostka
        aria-label: GitHub

format:
  html:
    toc: true
    embed-resources: false
    html-math-method: katex
    mainfont: "Inter V" # NotoSerif, Inter
    monofont: "Cascadia Mono"
    theme: journal # journal, flatly, darkly, sandstone
      # light: flatly
      # dark: darkly
    code-fold: false
    code-line-numbers: false
    code-copy: true
    code-overflow: wrap
    code-block-bg: false
    code-block-border-left: true
    highlight-style: github
    email-obfuscation: javascript
    # css: styles.css


title-block-banner: true
subtitle: "A work in progress"
date: today
author:
  - name: Benjamin Starostka
    email: benjamin.starostka@gmail.com

execute:
  freeze: auto

# metadata
keywords: []
license: CC
pagetitle: ""
subject: ""
title-meta: "Draft document"
author-meta: "Benjamin Starostka Jakobsen"
date-meta: ""
description-meta: ""